import type { Car } from '../../types';

const cars: Car[] = [
  {
    manufacturer: 'Toyota',
    model: 'Corolla',
    color: 'Red',
    price: 20000,
    year: 2021,
    engine: '1.8L I4',
    horsepower: 139,
    description: 'A reliable and fuel-efficient compact sedan.',
  },
  {
    manufacturer: 'Honda',
    model: 'Civic',
    color: 'Blue',
    price: 21000,
    year: 2022,
    engine: '2.0L I4',
    horsepower: 158,
    description: 'A sporty and efficient sedan with modern features.',
  },
  {
    manufacturer: 'Ford',
    model: 'Mustang',
    color: 'Black',
    price: 35000,
    year: 2023,
    engine: '5.0L V8',
    horsepower: 450,
    description: 'An iconic American muscle car with powerful performance.',
  },
  {
    manufacturer: 'Chevrolet',
    model: 'Camaro',
    color: 'Yellow',
    price: 37000,
    year: 2022,
    engine: '6.2L V8',
    horsepower: 455,
    description: 'A classic muscle car with aggressive styling.',
  },
  {
    manufacturer: 'BMW',
    model: '3 Series',
    color: 'White',
    price: 42000,
    year: 2023,
    engine: '2.0L Turbo I4',
    horsepower: 255,
    description: 'A luxury sports sedan with dynamic handling.',
  },
  {
    manufacturer: 'Audi',
    model: 'A4',
    color: 'Gray',
    price: 41000,
    year: 2022,
    engine: '2.0L Turbo I4',
    horsepower: 201,
    description: 'A refined sedan with advanced technology.',
  },
  {
    manufacturer: 'Mercedes',
    model: 'C-Class',
    color: 'Silver',
    price: 43000,
    year: 2023,
    engine: '2.0L Turbo I4',
    horsepower: 255,
    description: 'A premium sedan with comfort and style.',
  },
  {
    manufacturer: 'Volkswagen',
    model: 'Golf',
    color: 'Green',
    price: 23000,
    year: 2021,
    engine: '1.4L Turbo I4',
    horsepower: 147,
    description: 'A versatile hatchback with European flair.',
  },
  {
    manufacturer: 'Hyundai',
    model: 'Elantra',
    color: 'Blue',
    price: 19000,
    year: 2022,
    engine: '2.0L I4',
    horsepower: 147,
    description: 'A compact sedan with bold design and value.',
  },
  {
    manufacturer: 'Kia',
    model: 'Forte',
    color: 'Red',
    price: 18500,
    year: 2021,
    engine: '2.0L I4',
    horsepower: 147,
    description: 'A practical sedan with great warranty.',
  },
  {
    manufacturer: 'Mazda',
    model: 'Mazda3',
    color: 'Black',
    price: 21000,
    year: 2022,
    engine: '2.5L I4',
    horsepower: 186,
    description: 'A stylish compact car with sporty handling.',
  },
  {
    manufacturer: 'Nissan',
    model: 'Altima',
    color: 'White',
    price: 24000,
    year: 2023,
    engine: '2.5L I4',
    horsepower: 188,
    description: 'A midsize sedan with available AWD.',
  },
  {
    manufacturer: 'Subaru',
    model: 'Impreza',
    color: 'Silver',
    price: 22000,
    year: 2022,
    engine: '2.0L H4',
    horsepower: 152,
    description: 'A compact car with standard all-wheel drive.',
  },
  {
    manufacturer: 'Tesla',
    model: 'Model 3',
    color: 'Red',
    price: 48000,
    year: 2023,
    engine: 'Electric',
    horsepower: 283,
    description: 'A cutting-edge electric sedan with autopilot.',
  },
  {
    manufacturer: 'Lexus',
    model: 'IS',
    color: 'Blue',
    price: 39000,
    year: 2022,
    engine: '2.0L Turbo I4',
    horsepower: 241,
    description: 'A luxury sedan with sporty character.',
  },
  {
    manufacturer: 'Acura',
    model: 'ILX',
    color: 'Gray',
    price: 32000,
    year: 2021,
    engine: '2.4L I4',
    horsepower: 201,
    description: 'A compact luxury sedan with value.',
  },
  {
    manufacturer: 'Infiniti',
    model: 'Q50',
    color: 'Black',
    price: 37000,
    year: 2022,
    engine: '3.0L Turbo V6',
    horsepower: 300,
    description: 'A performance-oriented luxury sedan.',
  },
  {
    manufacturer: 'Volvo',
    model: 'S60',
    color: 'White',
    price: 36000,
    year: 2023,
    engine: '2.0L Turbo I4',
    horsepower: 250,
    description: 'A Scandinavian sedan with safety focus.',
  },
  {
    manufacturer: 'Jaguar',
    model: 'XE',
    color: 'Green',
    price: 45000,
    year: 2022,
    engine: '2.0L Turbo I4',
    horsepower: 247,
    description: 'A British sports sedan with luxury.',
  },
  {
    manufacturer: 'Alfa Romeo',
    model: 'Giulia',
    color: 'Red',
    price: 47000,
    year: 2023,
    engine: '2.0L Turbo I4',
    horsepower: 280,
    description: 'An Italian sedan with thrilling performance.',
  },
];

export default cars;
