import type { Laptop } from '../../types';

export const laptopStoreItems: Laptop[] = [
  {
    brand: 'Acer',
    model: 'MacBook Pro 1',
    processor: 'AMD Ryzen 5',
    ram: '16GB',
    storage: '256GB SSD',
    screenSize: 17.0,
    price: 1228,
    description: 'Top-seller worldwide.',
  },
  {
    brand: 'Acer',
    model: 'MacBook Pro 2',
    processor: 'Intel i5',
    ram: '32GB',
    storage: '512GB SSD',
    screenSize: 13.3,
    price: 1874,
    description: 'A must-have for enthusiasts.',
  },
  {
    brand: 'Lenovo',
    model: 'Blade 3',
    processor: 'M2',
    ram: '16GB',
    storage: '256GB SSD',
    screenSize: 16.0,
    price: 1165,
    description: 'A gripping read.',
  },
  {
    brand: 'Microsoft',
    model: 'Surface 4',
    processor: 'M2',
    ram: '32GB',
    storage: '1TB SSD',
    screenSize: 14.0,
    price: 1146,
    description: 'A must-have for enthusiasts.',
  },
  {
    brand: 'Acer',
    model: 'MacBook Pro 5',
    processor: 'AMD Ryzen 5',
    ram: '16GB',
    storage: '256GB SSD',
    screenSize: 15.6,
    price: 937,
    description: 'A must-have for enthusiasts.',
  },
  {
    brand: 'HP',
    model: 'Galaxy Book 6',
    processor: 'AMD Ryzen 5',
    ram: '16GB',
    storage: '512GB SSD',
    screenSize: 13.3,
    price: 2646,
    description: 'A gripping read.',
  },
  {
    brand: 'Razer',
    model: 'MacBook Air 7',
    processor: 'Intel i5',
    ram: '16GB',
    storage: '256GB SSD',
    screenSize: 17.0,
    price: 1921,
    description: 'Praised for depth and storytelling.',
  },
  {
    brand: 'Acer',
    model: 'VivoBook 8',
    processor: 'AMD Ryzen 5',
    ram: '8GB',
    storage: '256GB SSD',
    screenSize: 13.3,
    price: 900,
    description: 'A gripping read.',
  },
  {
    brand: 'Acer',
    model: 'Surface 9',
    processor: 'AMD Ryzen 5',
    ram: '16GB',
    storage: '512GB SSD',
    screenSize: 16.0,
    price: 1749,
    description: 'Top-seller worldwide.',
  },
  {
    brand: 'Asus',
    model: 'MacBook Pro 10',
    processor: 'AMD Ryzen 5',
    ram: '8GB',
    storage: '512GB SSD',
    screenSize: 15.6,
    price: 2379,
    description: 'Critically acclaimed.',
  },
  {
    brand: 'Samsung',
    model: 'Surface 11',
    processor: 'Intel i9',
    ram: '16GB',
    storage: '1TB SSD',
    screenSize: 13.3,
    price: 1768,
    description: 'Critically acclaimed.',
  },
  {
    brand: 'Microsoft',
    model: 'Blade 12',
    processor: 'AMD Ryzen 7',
    ram: '16GB',
    storage: '1TB SSD',
    screenSize: 17.0,
    price: 2986,
    description: 'A must-have for enthusiasts.',
  },
  {
    brand: 'Lenovo',
    model: 'MacBook Pro 13',
    processor: 'Intel i7',
    ram: '32GB',
    storage: '512GB SSD',
    screenSize: 17.0,
    price: 1754,
    description: 'A gripping read.',
  },
  {
    brand: 'Lenovo',
    model: 'Predator 14',
    processor: 'AMD Ryzen 7',
    ram: '16GB',
    storage: '256GB SSD',
    screenSize: 14.0,
    price: 2254,
    description: 'Critically acclaimed.',
  },
  {
    brand: 'Asus',
    model: 'ThinkPad 15',
    processor: 'AMD Ryzen 7',
    ram: '32GB',
    storage: '512GB SSD',
    screenSize: 15.6,
    price: 2705,
    description: 'Top-seller worldwide.',
  },
  {
    brand: 'Asus',
    model: 'ThinkPad 16',
    processor: 'AMD Ryzen 5',
    ram: '8GB',
    storage: '256GB SSD',
    screenSize: 16.0,
    price: 969,
    description: 'Top-seller worldwide.',
  },
  {
    brand: 'Samsung',
    model: 'XPS 17',
    processor: 'M2',
    ram: '16GB',
    storage: '256GB SSD',
    screenSize: 13.3,
    price: 2750,
    description: 'Praised for depth and storytelling.',
  },
  {
    brand: 'Microsoft',
    model: 'Surface 18',
    processor: 'Intel i9',
    ram: '32GB',
    storage: '1TB SSD',
    screenSize: 17.0,
    price: 2687,
    description: 'Critically acclaimed.',
  },
  {
    brand: 'MSI',
    model: 'Galaxy Book 19',
    processor: 'Intel i7',
    ram: '8GB',
    storage: '1TB SSD',
    screenSize: 16.0,
    price: 2181,
    description: 'A must-have for enthusiasts.',
  },
  {
    brand: 'Lenovo',
    model: 'XPS 20',
    processor: 'AMD Ryzen 7',
    ram: '16GB',
    storage: '1TB SSD',
    screenSize: 17.0,
    price: 998,
    description: 'A gripping read.',
  },
  {
    brand: 'HP',
    model: 'Galaxy Book 21',
    processor: 'AMD Ryzen 7',
    ram: '16GB',
    storage: '512GB SSD',
    screenSize: 13.3,
    price: 1298,
    description: 'A gripping read.',
  },
  {
    brand: 'Razer',
    model: 'Predator 22',
    processor: 'Intel i5',
    ram: '8GB',
    storage: '1TB SSD',
    screenSize: 14.0,
    price: 2881,
    description: 'Critically acclaimed.',
  },
  {
    brand: 'Razer',
    model: 'Surface 23',
    processor: 'Intel i5',
    ram: '8GB',
    storage: '256GB SSD',
    screenSize: 16.0,
    price: 2905,
    description: 'Praised for depth and storytelling.',
  },
  {
    brand: 'Lenovo',
    model: 'Surface 24',
    processor: 'AMD Ryzen 7',
    ram: '16GB',
    storage: '256GB SSD',
    screenSize: 16.0,
    price: 2804,
    description: 'A must-have for enthusiasts.',
  },
  {
    brand: 'Asus',
    model: 'Galaxy Book 25',
    processor: 'AMD Ryzen 7',
    ram: '16GB',
    storage: '1TB SSD',
    screenSize: 16.0,
    price: 2280,
    description: 'Praised for depth and storytelling.',
  },
];
