import type { Book } from '../../types';

export const bookStoreItems: Book[] = [
  {
    title: 'Foundation Vol 1',
    author: 'Jane Austen',
    genre: 'Thriller',
    yearPublished: 2017,
    pageCount: 545,
    price: 18,
    description: 'A must-have for enthusiasts.',
  },
  {
    title: 'The Handmaid’s Tale Vol 2',
    author: 'Stephen King',
    genre: 'History',
    yearPublished: 1996,
    pageCount: 202,
    price: 36,
    description: 'Praised for depth and storytelling.',
  },
  {
    title: 'The Hobbit Vol 3',
    author: 'Yuval Noah Harari',
    genre: 'History',
    yearPublished: 1998,
    pageCount: 450,
    price: 24,
    description: 'Praised for depth and storytelling.',
  },
  {
    title: 'The Hobbit Vol 4',
    author: 'Isaac Asimov',
    genre: 'Fantasy',
    yearPublished: 2004,
    pageCount: 326,
    price: 21,
    description: 'Top-seller worldwide.',
  },
  {
    title: 'Norwegian Wood Vol 5',
    author: 'George Orwell',
    genre: 'Thriller',
    yearPublished: 1950,
    pageCount: 384,
    price: 15,
    description: 'Praised for depth and storytelling.',
  },
  {
    title: 'Foundation Vol 6',
    author: 'Stephen King',
    genre: 'History',
    yearPublished: 1993,
    pageCount: 279,
    price: 15,
    description: 'Top-seller worldwide.',
  },
  {
    title: 'Outliers Vol 7',
    author: 'Malcolm Gladwell',
    genre: 'History',
    yearPublished: 2015,
    pageCount: 374,
    price: 21,
    description: 'Critically acclaimed.',
  },
  {
    title: 'Norwegian Wood Vol 8',
    author: 'James Clear',
    genre: 'Self-help',
    yearPublished: 2000,
    pageCount: 372,
    price: 36,
    description: 'Praised for depth and storytelling.',
  },
  {
    title: 'The Shining Vol 9',
    author: 'J.R.R. Tolkien',
    genre: 'Science Fiction',
    yearPublished: 1955,
    pageCount: 365,
    price: 20,
    description: 'A gripping read.',
  },
  {
    title: 'Atomic Habits Vol 10',
    author: 'Yuval Noah Harari',
    genre: 'History',
    yearPublished: 1972,
    pageCount: 196,
    price: 26,
    description: 'Critically acclaimed.',
  },
  {
    title: 'Atomic Habits Vol 11',
    author: 'James Clear',
    genre: 'Biography',
    yearPublished: 1993,
    pageCount: 692,
    price: 24,
    description: 'Praised for depth and storytelling.',
  },
  {
    title: 'Atomic Habits Vol 12',
    author: 'J.R.R. Tolkien',
    genre: 'Romance',
    yearPublished: 2022,
    pageCount: 429,
    price: 15,
    description: 'Top-seller worldwide.',
  },
  {
    title: 'The Hobbit Vol 13',
    author: 'Haruki Murakami',
    genre: 'Fantasy',
    yearPublished: 2012,
    pageCount: 609,
    price: 22,
    description: 'A gripping read.',
  },
  {
    title: '1984 Vol 14',
    author: 'Stephen King',
    genre: 'Romance',
    yearPublished: 1968,
    pageCount: 576,
    price: 13,
    description: 'Critically acclaimed.',
  },
  {
    title: '1984 Vol 15',
    author: 'Margaret Atwood',
    genre: 'Self-help',
    yearPublished: 2013,
    pageCount: 334,
    price: 27,
    description: 'Top-seller worldwide.',
  },
  {
    title: '1984 Vol 16',
    author: 'James Clear',
    genre: 'Science Fiction',
    yearPublished: 1954,
    pageCount: 254,
    price: 36,
    description: 'Top-seller worldwide.',
  },
  {
    title: 'Atomic Habits Vol 17',
    author: 'James Clear',
    genre: 'Thriller',
    yearPublished: 1997,
    pageCount: 270,
    price: 21,
    description: 'A must-have for enthusiasts.',
  },
  {
    title: 'The Handmaid’s Tale Vol 18',
    author: 'Yuval Noah Harari',
    genre: 'Romance',
    yearPublished: 2023,
    pageCount: 581,
    price: 25,
    description: 'Praised for depth and storytelling.',
  },
  {
    title: 'Atomic Habits Vol 19',
    author: 'Jane Austen',
    genre: 'Fantasy',
    yearPublished: 2008,
    pageCount: 309,
    price: 16,
    description: 'A must-have for enthusiasts.',
  },
  {
    title: 'Sapiens Vol 20',
    author: 'J.R.R. Tolkien',
    genre: 'Science Fiction',
    yearPublished: 1992,
    pageCount: 163,
    price: 27,
    description: 'Critically acclaimed.',
  },
  {
    title: 'Foundation Vol 21',
    author: 'Haruki Murakami',
    genre: 'Science Fiction',
    yearPublished: 1968,
    pageCount: 569,
    price: 17,
    description: 'A must-have for enthusiasts.',
  },
  {
    title: '1984 Vol 22',
    author: 'James Clear',
    genre: 'Thriller',
    yearPublished: 2001,
    pageCount: 311,
    price: 34,
    description: 'A must-have for enthusiasts.',
  },
  {
    title: 'The Hobbit Vol 23',
    author: 'George Orwell',
    genre: 'History',
    yearPublished: 2015,
    pageCount: 621,
    price: 37,
    description: 'Critically acclaimed.',
  },
  {
    title: '1984 Vol 24',
    author: 'Jane Austen',
    genre: 'Romance',
    yearPublished: 2021,
    pageCount: 259,
    price: 20,
    description: 'Praised for depth and storytelling.',
  },
  {
    title: 'Outliers Vol 25',
    author: 'Haruki Murakami',
    genre: 'Romance',
    yearPublished: 2002,
    pageCount: 455,
    price: 24,
    description: 'Praised for depth and storytelling.',
  },
];
